// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlBoTx.Net.EFCore;

#nullable disable

namespace SqlBoTx.Net.DbManager.Migrations
{
    [DbContext(typeof(SqlBotxDBContext))]
    [Migration("20260303072954_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("WolverineEnabled", "true");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.BusinessMetricJoinPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("alias")
                        .HasComment("目标表别名");

                    b.Property<int>("BusinessMetricId")
                        .HasColumnType("int")
                        .HasColumnName("business_metric_id")
                        .HasComment("业务指标Id");

                    b.Property<string>("JoinType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(255)")
                        .HasDefaultValue("LEFT JOIN")
                        .HasColumnName("join_type")
                        .HasComment("连接类型");

                    b.Property<string>("OnCondition")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("on_condition")
                        .HasComment("连接条件");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order")
                        .HasComment("排序");

                    b.Property<int>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("table_id")
                        .HasComment("目标表Id）");

                    b.HasKey("Id");

                    b.HasIndex("BusinessMetricId");

                    b.HasIndex("TableId");

                    b.ToTable("business_metric_join_path", null, t =>
                        {
                            t.HasComment("业务指标路径");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.BusinessObjectiveMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("alias")
                        .HasComment("近义词/检索关键词");

                    b.Property<int>("BusinessObjectiveId")
                        .HasColumnType("int")
                        .HasColumnName("business_objective_id")
                        .HasComment("外键-归属业务模块Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("指标解释");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("expression")
                        .HasComment("计算公式（非原子）");

                    b.Property<string>("MainAlias")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(255)")
                        .HasDefaultValue("Main")
                        .HasColumnName("main_alias");

                    b.Property<int>("MainTableId")
                        .HasColumnType("int")
                        .HasColumnName("main_table_id")
                        .HasComment("依赖主体-主表");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("metric_code")
                        .HasComment("指标编码");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("metric_name")
                        .HasComment("指标名称");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasComment("生命周期");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectiveId");

                    b.HasIndex("MainTableId");

                    b.ToTable("business_objective_metric", null, t =>
                        {
                            t.HasComment("业务指标");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("business_name")
                        .HasComment("业务名称");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("业务解释");

                    b.Property<string>("Synonyms")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("synonyms")
                        .HasComment("近义词");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("business_objective", null, t =>
                        {
                            t.HasComment("业务目标");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjectiveField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinesBIRole")
                        .HasColumnType("int")
                        .HasColumnName("busines_birole")
                        .HasComment("业务分析角色");

                    b.Property<int>("BusinessObjectiveId")
                        .HasColumnType("int")
                        .HasColumnName("business_objective_id")
                        .HasComment("外键-归属业务模块Id");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("字段说明");

                    b.Property<int?>("DimensionLayer")
                        .HasColumnType("int")
                        .HasColumnName("dimension_layer")
                        .HasComment("维度层次");

                    b.Property<int>("FieldId")
                        .HasColumnType("int")
                        .HasColumnName("field_id")
                        .HasComment("表字段ID");

                    b.Property<int?>("MetricLayer")
                        .HasColumnType("int")
                        .HasColumnName("metric_layer")
                        .HasComment("度量层次");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("name")
                        .HasComment("字段名称");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectiveId");

                    b.HasIndex("FieldId");

                    b.ToTable("business_objective_field", null, t =>
                        {
                            t.HasComment("业务目标字段");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.DatabaseConnections.DatabaseConnection", b =>
                {
                    b.Property<int>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("connection_id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectionId"));

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("connection_name")
                        .HasComment("连接名称");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("connection_string")
                        .HasComment("数据库连接字符串");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int")
                        .HasColumnName("connection_type")
                        .HasComment("连接类型（1=SQL Server、2=MySQL、3=Oracle、4=PostgreSQL等）");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("描述信息");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_date")
                        .HasComment("最后修改时间");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.Property<string>("UserPassword")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("user_password")
                        .HasComment("密码");

                    b.HasKey("ConnectionId");

                    b.ToTable("database_connection", null, t =>
                        {
                            t.HasComment("数据库连接配置");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableFields.TableField", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("field_id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("column_name")
                        .HasComment("字段名称");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("data_type")
                        .HasComment("字段数据类型");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("default_value")
                        .HasComment("默认值");

                    b.Property<string>("FieldDescription")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("field_description")
                        .HasComment("字段说明");

                    b.Property<string>("FieldName")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("field_name")
                        .HasComment("字段中文名称");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available")
                        .HasComment("是否可用");

                    b.Property<bool>("IsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_identity")
                        .HasComment("是否为自增字段");

                    b.Property<bool>("IsNullable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_nullable")
                        .HasComment("是否允许为空");

                    b.Property<bool>("IsPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary_key")
                        .HasComment("是否为主键");

                    b.Property<int>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("table_id")
                        .HasComment("外键");

                    b.HasKey("FieldId");

                    b.HasIndex("TableId");

                    b.ToTable("table_field", null, t =>
                        {
                            t.HasComment("表字段明细信息");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableRelationships.TableRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("conditions")
                        .HasComment("关联条件");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<string>("RelationshipDescription")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("relationship_description")
                        .HasComment("关系类型");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int")
                        .HasColumnName("relationship_type")
                        .HasComment("关系类型");

                    b.Property<int>("SourceTableId")
                        .HasColumnType("int")
                        .HasColumnName("source_table_id")
                        .HasComment("源表ID");

                    b.Property<int>("TargetTableId")
                        .HasColumnType("int")
                        .HasColumnName("target_table_id")
                        .HasComment("目标表ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("SourceTableId");

                    b.HasIndex("TargetTableId");

                    b.ToTable("table_relationship", null, t =>
                        {
                            t.HasComment("表关系维护");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructure", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("table_id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int")
                        .HasColumnName("connection_id")
                        .HasComment("外键");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("表描述");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("display_name")
                        .HasComment("显示名称");

                    b.Property<int>("FieldCount")
                        .HasColumnType("int")
                        .HasColumnName("field_count")
                        .HasComment("字段数量");

                    b.Property<string>("Granularity")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("granularity")
                        .HasComment("颗粒度描述");

                    b.Property<int?>("GranularityLevel")
                        .HasColumnType("int")
                        .HasColumnName("granularity_level")
                        .HasComment("颗粒度级别");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("table_name")
                        .HasComment("表名");

                    b.HasKey("TableId");

                    b.HasIndex("ConnectionId");

                    b.ToTable("table_structure", null, t =>
                        {
                            t.HasComment("数据库表结构");
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.BusinessMetricJoinPath", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessMetrics.BusinessObjectiveMetric", null)
                        .WithMany("JoinPaths")
                        .HasForeignKey("BusinessMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.BusinessObjectiveMetric", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", "BusinessObjective")
                        .WithMany("Metrics")
                        .HasForeignKey("BusinessObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "MainTable")
                        .WithMany()
                        .HasForeignKey("MainTableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BusinessObjective");

                    b.Navigation("MainTable");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", b =>
                {
                    b.OwnsMany("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjectiveDependencyTable", "DependencyTables", b1 =>
                        {
                            b1.Property<int>("BusinessObjectiveId")
                                .HasColumnType("int")
                                .HasColumnName("business_objective_id");

                            b1.Property<int>("TableId")
                                .HasColumnType("int")
                                .HasColumnName("table_id");

                            b1.HasKey("BusinessObjectiveId", "TableId");

                            b1.ToTable("business_objective_dependency_table", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BusinessObjectiveId");
                        });

                    b.Navigation("DependencyTables");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjectiveField", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", "BusinessObjective")
                        .WithMany("Fields")
                        .HasForeignKey("BusinessObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.TableFields.TableField", "TableField")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BusinessObjective");

                    b.Navigation("TableField");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableFields.TableField", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", null)
                        .WithMany("TableFields")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableRelationships.TableRelationship", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "SourceTable")
                        .WithMany("SourceTableRelationships")
                        .HasForeignKey("SourceTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "TargetTable")
                        .WithMany("TargetTableRelationships")
                        .HasForeignKey("TargetTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceTable");

                    b.Navigation("TargetTable");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructure", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.DatabaseConnections.DatabaseConnection", null)
                        .WithMany("TableStructures")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.BusinessObjectiveMetric", b =>
                {
                    b.Navigation("JoinPaths");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.DatabaseConnections.DatabaseConnection", b =>
                {
                    b.Navigation("TableStructures");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructure", b =>
                {
                    b.Navigation("SourceTableRelationships");

                    b.Navigation("TableFields");

                    b.Navigation("TargetTableRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
