// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlBoTx.Net.EFCore;

#nullable disable

namespace SqlBoTx.Net.DbManager.Migrations
{
    [DbContext(typeof(SqlBotxDBContext))]
    partial class SqlBotxDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("WolverineEnabled", "true");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessEntities.DomainEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("alias");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description");

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("name");

                    b.Property<int>("ReferenceConnectId")
                        .HasColumnType("int")
                        .HasColumnName("reference_connect_id");

                    b.Property<int>("ReferenceTableId")
                        .HasColumnType("int")
                        .HasColumnName("reference_table_id");

                    b.Property<string>("Tags")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("ReferenceConnectId");

                    b.HasIndex("ReferenceTableId");

                    b.ToTable("domain_entity", null, t =>
                        {
                            t.HasComment("DomainEntity");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessEntities.DomainEntityAttr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnId")
                        .HasColumnType("int")
                        .HasColumnName("column_id")
                        .HasComment("引用库字段ID");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("column_name")
                        .HasComment("属性列名");

                    b.Property<int>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("data_type")
                        .HasComment("数据类型");

                    b.Property<string>("DataTypeSchema")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("data_type_schema")
                        .HasComment("数据类型概要（用来描述取值）");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("default_value")
                        .HasComment("默认值");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("字段说明（字段额外的解释）");

                    b.Property<int?>("DimensionCategory")
                        .HasColumnType("int")
                        .HasColumnName("dimension_category")
                        .HasComment("维度分类（SemanticType = Dimension 时有效）");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("entity_id")
                        .HasComment("实体ID");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required")
                        .HasComment("是否必要");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("label")
                        .HasComment("属性名称");

                    b.Property<int>("SemanticType")
                        .HasColumnType("int")
                        .HasColumnName("semantic_type")
                        .HasComment("语义类型");

                    b.Property<int>("StructureRole")
                        .HasColumnType("int")
                        .HasColumnName("structure_role")
                        .HasComment("结构语义");

                    b.Property<int?>("SupportedAggregations")
                        .HasColumnType("int")
                        .HasColumnName("supported_aggregations")
                        .HasComment("仅当 SemanticType = Measure 时有效。可使用的度量函数");

                    b.Property<int?>("TimeGranularity")
                        .HasColumnType("int")
                        .HasColumnName("time_granularity")
                        .HasComment("时间粒度（SemanticType = DateTime 时有效）");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("EntityId");

                    b.ToTable("domain_entity_attr", null, t =>
                        {
                            t.HasComment("实体属性");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessEntities.DomainEntityRel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    b.Property<int>("CascadeDelete")
                        .HasColumnType("int")
                        .HasColumnName("cascade_delete")
                        .HasComment("是否级联删除");

                    b.Property<string>("InverseOf")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("inverse_of")
                        .HasComment("反向关系Id");

                    b.Property<string>("JoinConditions")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("join_conditions")
                        .HasComment("关联条件");

                    b.Property<string>("SourceCardinality")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("source_cardinality")
                        .HasComment("源端基数（One/Many）");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("source_entity_id")
                        .HasComment("源实体标识符");

                    b.Property<string>("SourceRole")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("source_role")
                        .HasComment("源角色名称");

                    b.Property<string>("TargetCardinality")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("target_cardinality")
                        .HasComment("目标端基数（One/Many）");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("target_entity_id")
                        .HasComment("目标实体标识符");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("target_role")
                        .HasComment("目标角色名称");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type")
                        .HasComment("关联类型");

                    b.HasKey("Id");

                    b.HasIndex("SourceEntityId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("domain_entity_rel", null, t =>
                        {
                            t.HasComment("实体关系");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.DomainMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("alias")
                        .HasComment("近义词/检索关键词");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("指标解释");

                    b.Property<int?>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id")
                        .HasComment("外键-归属业务模块Id");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("expression")
                        .HasComment("计算公式（非原子）");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("metric_code")
                        .HasComment("指标编码");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("metric_name")
                        .HasComment("指标名称");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("scope")
                        .HasComment("作用域");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasComment("生命周期");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("domain_metric", null, t =>
                        {
                            t.HasComment("业务指标");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.MetricFieldPlaceholder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttrId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("attr_id")
                        .HasComment("属性Id");

                    b.Property<string>("AttrName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("attr_name")
                        .HasComment("属性名");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("entity_id")
                        .HasComment("归属实体Id");

                    b.Property<int>("Index")
                        .HasColumnType("int")
                        .HasColumnName("index")
                        .HasComment("占位符序号");

                    b.Property<int>("MetricId")
                        .HasColumnType("int")
                        .HasColumnName("metric_id")
                        .HasComment("指标外键");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.ToTable("metric_field_placeholder", null, t =>
                        {
                            t.HasComment("指标字段占位符");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("business_name")
                        .HasComment("业务域名称");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("业务解释");

                    b.Property<string>("KeyWords")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("key_words")
                        .HasComment("关键词：快速定位该领域，而非近义词");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id")
                        .HasComment("父业务域ID");

                    b.Property<string>("Summary")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("summary")
                        .HasComment("业务域总结");

                    b.Property<string>("Synonyms")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("synonyms")
                        .HasComment("近义词");

                    b.Property<string>("Tags")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("tags")
                        .HasComment("领域标签：核心域、支撑域、通用域、系统域");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("business_objective", null, t =>
                        {
                            t.HasComment("业务域");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.DatabaseConnections.DatabaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("connection_name")
                        .HasComment("连接名称");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("connection_string")
                        .HasComment("数据库连接字符串");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int")
                        .HasColumnName("connection_type")
                        .HasComment("连接类型（1=SQL Server、2=MySQL、3=Oracle、4=PostgreSQL等）");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("描述信息");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_date")
                        .HasComment("最后修改时间");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.Property<string>("UserPassword")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("user_password")
                        .HasComment("密码");

                    b.HasKey("Id");

                    b.ToTable("database_connection", null, t =>
                        {
                            t.HasComment("数据库连接配置");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.DomainTerms.DomainTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("alias")
                        .HasComment("别名近义词");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("解释说明");

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id")
                        .HasComment("所属业务域ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("name")
                        .HasComment("术语名");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("domain_term", null, t =>
                        {
                            t.HasComment("领域术语");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableRelationships.TableRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("conditions")
                        .HasComment("关联条件");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<string>("RelationshipDescription")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("relationship_description")
                        .HasComment("关系类型");

                    b.Property<int>("SourceCardinality")
                        .HasColumnType("int")
                        .HasColumnName("source_cardinality")
                        .HasComment("源端基数（One/Many）");

                    b.Property<int>("SourceTableId")
                        .HasColumnType("int")
                        .HasColumnName("source_table_id")
                        .HasComment("源表ID");

                    b.Property<int>("TargetCardinality")
                        .HasColumnType("int")
                        .HasColumnName("target_cardinality")
                        .HasComment("目标端基数（One/Many）");

                    b.Property<int>("TargetTableId")
                        .HasColumnType("int")
                        .HasColumnName("target_table_id")
                        .HasComment("目标表ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("SourceTableId");

                    b.HasIndex("TargetTableId");

                    b.ToTable("table_relationship", null, t =>
                        {
                            t.HasComment("表关系维护");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructure", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("table_id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("Alias")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("alias")
                        .HasComment("别名");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int")
                        .HasColumnName("connection_id")
                        .HasComment("数据库连接ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("表描述");

                    b.Property<int>("FieldCount")
                        .HasColumnType("int")
                        .HasColumnName("field_count")
                        .HasComment("字段数量");

                    b.Property<string>("SchemaName")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("schema_name")
                        .HasComment("模式");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("table_name")
                        .HasComment("表名");

                    b.HasKey("TableId");

                    b.HasIndex("ConnectionId");

                    b.ToTable("table_structure", null, t =>
                        {
                            t.HasComment("数据库表结构");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructureColumn", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("field_id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("column_name")
                        .HasComment("字段名称");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("data_type")
                        .HasComment("字段数据类型");

                    b.Property<string>("DataTypeSchema")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("data_type_schema")
                        .HasComment("类型描述");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("default_value")
                        .HasComment("默认值");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("字段说明");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(255)")
                        .HasDefaultValue("False")
                        .HasColumnName("expression")
                        .HasComment("表达式");

                    b.Property<string>("Indexs")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("indexs")
                        .HasComment("索引");

                    b.Property<bool>("IsComputed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_computed")
                        .HasComment("是否计算列");

                    b.Property<bool>("IsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_identity")
                        .HasComment("是否为自增字段");

                    b.Property<bool>("IsIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_index")
                        .HasComment("是否索引");

                    b.Property<bool>("IsPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary_key")
                        .HasComment("是否为主键");

                    b.Property<bool>("IsReference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reference")
                        .HasComment("外键引用");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required")
                        .HasComment("是否必填");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique")
                        .HasComment("是否唯一");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("label")
                        .HasComment("标题");

                    b.Property<string>("ReferenceColumn")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("reference_column")
                        .HasComment("引用字段");

                    b.Property<string>("ReferenceTableName")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("reference_table_name")
                        .HasComment("引用表名");

                    b.Property<int>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("table_id")
                        .HasComment("外键");

                    b.HasKey("FieldId");

                    b.HasIndex("TableId");

                    b.ToTable("table_structure_column", null, t =>
                        {
                            t.HasComment("表字段明细信息");
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessEntities.DomainEntity", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", "Domain")
                        .WithMany("Entities")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.DatabaseConnections.DatabaseConnection", "Database")
                        .WithMany()
                        .HasForeignKey("ReferenceConnectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "Table")
                        .WithMany()
                        .HasForeignKey("ReferenceTableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Database");

                    b.Navigation("Domain");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessEntities.DomainEntityAttr", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructureColumn", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.BusinessEntities.DomainEntity", "Entity")
                        .WithMany("Attrs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SqlBoTx.Net.Domain.DomainEntities.ForeignKeyMetaData", "ForeignKeyMetaData", b1 =>
                        {
                            b1.Property<int>("DomainEntityAttrId");

                            b1.Property<string>("TargetEntityId");

                            b1.Property<int>("Type");

                            b1.HasKey("DomainEntityAttrId");

                            b1.ToTable("domain_entity_attr");

                            b1.ToJson("ForeignKeyMetaData");

                            b1.WithOwner()
                                .HasForeignKey("DomainEntityAttrId");

                            b1.OwnsOne("SqlBoTx.Net.Domain.DomainEntities.PolymorphicForeignKey", "Polymorphic", b2 =>
                                {
                                    b2.Property<int>("ForeignKeyMetaDataDomainEntityAttrId");

                                    b2.HasKey("ForeignKeyMetaDataDomainEntityAttrId");

                                    b2.ToTable("domain_entity_attr");

                                    b2.WithOwner()
                                        .HasForeignKey("ForeignKeyMetaDataDomainEntityAttrId");

                                    b2.OwnsMany("SqlBoTx.Net.Domain.DomainEntities.PolymorphicMapping", "Mappings", b3 =>
                                        {
                                            b3.Property<int>("PolymorphicForeignKeyForeignKeyMetaDataDomainEntityAttrId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAddOrUpdate();

                                            b3.Property<string>("DiscriminatorColumn")
                                                .IsRequired();

                                            b3.Property<string>("DiscriminatorValue")
                                                .IsRequired();

                                            b3.Property<string>("TargetEntityId")
                                                .IsRequired();

                                            b3.HasKey("PolymorphicForeignKeyForeignKeyMetaDataDomainEntityAttrId", "__synthesizedOrdinal");

                                            b3.ToTable("domain_entity_attr");

                                            b3.WithOwner()
                                                .HasForeignKey("PolymorphicForeignKeyForeignKeyMetaDataDomainEntityAttrId");
                                        });

                                    b2.Navigation("Mappings");
                                });

                            b1.Navigation("Polymorphic");
                        });

                    b.Navigation("Column");

                    b.Navigation("Entity");

                    b.Navigation("ForeignKeyMetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessEntities.DomainEntityRel", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessEntities.DomainEntity", "SourceEntity")
                        .WithMany("SourceRels")
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.BusinessEntities.DomainEntity", "TargetEntity")
                        .WithMany("TargetRels")
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceEntity");

                    b.Navigation("TargetEntity");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.DomainMetric", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", "Domain")
                        .WithMany("Metrics")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.MetricFieldPlaceholder", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessMetrics.DomainMetric", "DomainMetric")
                        .WithMany("Placeholders")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomainMetric");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.DomainTerms.DomainTerm", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", "Domain")
                        .WithMany("Terms")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableRelationships.TableRelationship", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "SourceTable")
                        .WithMany("SourceTableRelationships")
                        .HasForeignKey("SourceTableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "TargetTable")
                        .WithMany("TargetTableRelationships")
                        .HasForeignKey("TargetTableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceTable");

                    b.Navigation("TargetTable");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructure", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.DatabaseConnections.DatabaseConnection", null)
                        .WithMany("TableStructures")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructureColumn", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.TableStructures.TableStructure", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessEntities.DomainEntity", b =>
                {
                    b.Navigation("Attrs");

                    b.Navigation("SourceRels");

                    b.Navigation("TargetRels");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessMetrics.DomainMetric", b =>
                {
                    b.Navigation("Placeholders");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.BusinessObjectives.BusinessObjective", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Entities");

                    b.Navigation("Metrics");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.DatabaseConnections.DatabaseConnection", b =>
                {
                    b.Navigation("TableStructures");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.TableStructures.TableStructure", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("SourceTableRelationships");

                    b.Navigation("TargetTableRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
